version: '3.5'

services:
  littleua-db:
    container_name: littleua-db
    image: postgres
    environment:
      POSTGRES_USER: littleua
      POSTGRES_PASSWORD: littleua
      POSTGRES_DB: betest
      PGDATA: /data/postgres
    volumes:
      - littleua-db-volume:/data/postgres
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"

volumes:
  littleua-db-volume:
